### ISSUE TITLE
Add Swift Package Manager support

### ISSUE THREAD

**Issue by ole** [ole/Ampere#1]
It might make sense to change the directory structure to the one expected by the Swift Package Manager. We could then use `swift package generate-xcodeproj` to create the Xcode project.

I can’t do this at the moment because:
- [x] SwiftPM only supports macOS and Linux at this point (not iOS).
- [x] The units and measurement APIs require macOS 10.12.
- [x] I haven’t upgraded to macOS 10.12 yet.

**Comment by ole** [comment]
See Daniel Duan's article about automating testing for all permutations of CocoaPods/Carthage/SwiftPM and macOS/iOS/tvOS/watchOS: http://dduan.net/2016/10/10/distribution-tests/

**Comment by ole** [comment]
SwiftPM currently hardcodes the macOS deployment target to 10.10 (Ampere needs 10.12). Here is a workaround, but it's not in 3.0. https://github.com/apple/swift-package-manager/pull/715

**Comment by billabt** [comment]
What version of the Swift toolchain has the fix for this problem in it?

Using swift-3.0.1-RELEASE, I see the default target overriding my specified target...
```
other-args: ["-j8","-D","SWIFT_PACKAGE","-Onone","-g","-enable-testing","-F","/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks","-target","x86_64-apple-macosx10.12","-target","x86_64-apple-macosx10.10","-sdk","/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk","-Xcc","-fmodule-map-file=/Users/babt/Source/IBMSwift/Open Source/BlueRSA/Packages/CommonCrypto-0.1.4/module.modulemap","-module-cache-path","/Users/babt/Source/IBMSwift/Open Source/BlueRSA/.build/debug/ModuleCache"]
```

**Comment by ole** [comment]
~~~bash
$ cd swift-source
$ swift/utils/update-checkout
$ cd swiftpm
$ git branch -r --contains 28e221b
  origin/HEAD -> origin/master
  origin/master
  origin/master-next
  origin/swift-3.1-branch
~~~

So it seems this will be part of Swift 3.1.

**Comment by ole** [comment]
See #9 for a version that builds with the Swift Package Manager (using a recent Swift snapshot).

**Comment by ole** [comment]
Taking this issue up again now that Xcode 11 has SwiftPM support. My plan is to fully migrate to SwiftPM and delete the Xcode project.

Checklist:

- [x] Add Package manifest
- [x] Change directory structure to accomodate SwiftPM
- [x] Delete Xcode project
- [x] Set macOS and iOS deployment targets
- [ ] Add Docker config for testing under Linux
- [x] Update .gitignore
- [x] Update usage instructions in readme
- [ ] Update .travis.yml to use Docker or use GitHub Actions
