### ISSUE TITLE
Tagged Version

### ISSUE THREAD

**Issue by Jeehut** [ole/Ampere#10]
Thanks @ole for putting your articles code into this library. When reading them through I thought "that would be great as a library for this project" and I've just included it in one of our projects. Builds fine with Carthage, but it would be great to have a tagged version so we don't have to specify the master branch. That would prevent unwanted updates including breaking changes.

Currently we include this in our Cartfile:

```
github "ole/Ampere" "master"
```

I'd rather see something like this though (even if it is a 0 major version, it's better than master):

```
github "ole/Ampere" ~> 1.0
```

**Comment by ole** [comment]
Thanks for the reminder. I just pushed a [0.1 tag](https://github.com/ole/Ampere/releases/tag/0.1).
