### ISSUE TITLE
No readability-improving typealiases?

### ISSUE THREAD

**Issue by Jeehut** [ole/Ampere#11]
In your first article you state:

> Now add one typealias per unit class to get rid of the UnitLength prefix and I really start to like it:

I just searched the code though and couldn't find things like `typealias Length = Measurement<UnitLength>` in the code. Why is this, wouldn't it make sense to include them in Ampere, too? I'm now adding them manually to my project, but I wonder the rationale behind not adding them. Not to pollute the API? Dunno, seems like they make sense to me. Would be great to have them IMHO. 👍

**Comment by Jeehut** [comment]
By the way, here's the content of my `HandyMeasurements.swift` file:

``` Swift
import Foundation

typealias Acceleration = Measurement<UnitAcceleration>
typealias Angle = Measurement<UnitAngle>
typealias Area = Measurement<UnitArea>
typealias ConcentrationMass = Measurement<UnitConcentrationMass>
typealias Dispersion = Measurement<UnitDispersion>
typealias Duration = Measurement<UnitDuration>
typealias ElectricCharge = Measurement<UnitElectricCharge>
typealias ElectricCurrent = Measurement<UnitElectricCurrent>
typealias ElectricPotentialDifference = Measurement<UnitElectricPotentialDifference>
typealias ElectricResistance = Measurement<UnitElectricResistance>
typealias Energy = Measurement<UnitEnergy>
typealias Frequency = Measurement<UnitFrequency>
typealias FuelEfficiency = Measurement<UnitFuelEfficiency>
typealias Length = Measurement<UnitLength>
typealias Illuminance = Measurement<UnitIlluminance>
typealias Mass = Measurement<UnitMass>
typealias Power = Measurement<UnitPower>
typealias Pressure = Measurement<UnitPressure>
typealias Speed = Measurement<UnitSpeed>
typealias Temperature = Measurement<UnitTemperature>
typealias Volume = Measurement<UnitVolume>
```

**Comment by ole** [comment]
Thanks for the suggestion. There was no deep rationale behind not including them at the time. But now that you made me think about it, I don't think it's the right thing to do. A library should be as familiar as possible to users; if it needlessly used a different terminology than the official APIs (or other libraries), I don't think that would be in the interest of most users.

If app developers define their own typealiases in code that nobody outside their team interacts with, that's much less problematic, of course.

I'm closing this, but feel free to comment if you'd like to discuss this further.

**Comment by Jeehut** [comment]
I agree for the most part. But at the same time I don't think it would hurt much as the names are chosen exactly like the Unit suffixes. Also if people see multiplication and division between different measurement types, they'll need to look up the Ampere documentation anyways. If your argument is "people will immediately understand that length/duration=speed" then the same argument is true for recognizing the types, also. On top of that the alt-clicking on the type they'll immediately see that it's a type alias for Measurement, if they are curious (that's what I do, if I don't know a type yet).

But having all that said, I'm absolutely okay with your decision, I don't think it'll make a huge difference. In any case my code above can be copied over into projects if people are interested in the typealiases anyway. Thanks for getting back to this and keep on writing those useful posts! 👍
